language: rust

cache: cargo

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly

notifications:
    email:
        recipients:
            - dillonhammond@gmail.com
        on_success: change
        on_failure: always
